### ISSUE TITLE
Wrong autoupdate link in yabairc

### ISSUE THREAD

**Issue by dominiklohmann** [kkga/dotfiles#1]
Hey,

I have this (bad?) habit of looking for dotfiles repos of people that comment on yabai to look for ideas. I noticed that you're using my autoupdate script, but are using an outdated version.

The version I first published was fixed to the first revision of the gist, and I cannot overwrite the short-url for it. That's why I changed it from git.io/yabai-autoupdate to git.io/update-yabai.

The script has gotten much more robust since then and does no longer spawn a terminal. It also installs updates automatically now and only updates the scripting addition when needed, and only then asks for a password.

Here's the script. You can see changes in the Revisions tab.
https://gist.github.com/dominiklohmann/637ecc399fb2a49252427a84bc2cd3ae

If you have any questions/suggestions, feel free to ask.

**Comment by kkga** [comment]
oh hi there 😄 

the update script has been pretty helpful so far, thanks for putting it together!
changed the url to the new one, works great 👌

---
On a side note, while we're here...
I'm using yabai's events to refresh a custom [ubersicht bar](https://github.com/kkga/nibar) I put together here https://github.com/kkga/dotfiles/blob/master/.yabairc#L50

What annoys me is that refreshing isn't instant as is the case when using yabai's default bar. I'm not sure which part of the setup adds a ~1s delay, whether it's yabai events, ubersicht refresh, or the shell command in between...
Wondering if you have any ideas how to make it instant, thanks in advance 👍

**Comment by dominiklohmann** [comment]
There's three parts to the delay, but it's mostly Übersicht.

- yabai triggers the action asynchronously after the event happened. You can test the speed of this by echoing something and looking at the log file. It's quite fast. 
- `osascript` compiles your script and then runs it.
- Übersicht replies to events quite slowly.

I can seee two parts where you can shave off time:

- All your space-changing hotkeys should invoke the script as a background process before invoking yabai
- The AppleScript should be precompiled using `osacompile`

Also just a word of warning regarding the update script, it'll probably change a fair bit over the coming weeks as I'm trying to adjust it to work with Catalina, where codesigning requirements changed a lot.
